[package]
name = "automation-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
can-dbc = "5.0.0"
pcan-basic = "1.0.2"
nom = { version = "7.1", features = ["alloc"] }
